/**
 * INDUSTRYxLINK – IFS Loops Agentic Layer
 * Shared types and interfaces for all agents
 */

/** Represents the parsed output of the Visit Request Agent */
export interface VisitRequirements {
  studentCount: number;
  yearOfStudy?: number;
  degreeProgram: string;
  topicInterests: string[];
  preferredMonth?: string;
  preferredDateRange?: { start: Date; end: Date };
  universityId: string;
  coordinatorId: string;
}

/** Represents a company match with its suitability score */
export interface CompanyMatch {
  companyId: string;
  companyName: string;
  opportunityId: string;
  suitabilityScore: number;
  matchDetails: {
    degreeMatch: number;
    topicMatch: number;
    capacityMatch: number;
    dateCompatibility: number;
    locationScore: number;
    previousEngagement: number;
  };
}

/** Represents the capacity check result for a company */
export interface CapacityResult {
  companyId: string;
  opportunityId: string;
  availableSeats: number;
  totalCapacity: number;
  isAvailable: boolean;
  existingBookings: number;
}

/** Represents a communication task */
export interface CommunicationTask {
  type: 'VISIT_REQUEST' | 'CONFIRMATION' | 'REJECTION' | 'REGISTRATION' | 'FOLLOW_UP';
  recipientType: 'COMPANY' | 'STUDENT' | 'COORDINATOR';
  recipientEmail: string;
  subject: string;
  body: string;
  metadata?: Record<string, unknown>;
}

/** Represents a scheduled reminder */
export interface ReminderSchedule {
  visitId: string;
  reminderType: 'ONE_WEEK' | 'THREE_DAYS' | 'ONE_DAY' | 'CUSTOM';
  scheduledDate: Date;
  recipients: string[];
  message: string;
  status: 'SCHEDULED' | 'SENT' | 'CANCELLED';
}

/** Represents an attendance record entry */
export interface AttendanceEntry {
  studentId: string;
  studentName?: string;
  present: boolean;
  checkInTime?: Date;
  notes?: string;
}

/** Represents the final report generated by the Report Agent */
export interface VisitReportData {
  visitId: string;
  universityName: string;
  companyName: string;
  visitDate: Date;
  totalRegistered: number;
  totalAttended: number;
  attendanceRate: number;
  noShows: number;
  summary: string;
  recommendations?: string[];
}

/** Status of an agent's execution */
export type AgentStatus = 'IDLE' | 'RUNNING' | 'COMPLETED' | 'FAILED';

/** Log entry for agent actions (for audit trail) */
export interface AgentLog {
  agentName: string;
  action: string;
  timestamp: Date;
  input?: unknown;
  output?: unknown;
  status: AgentStatus;
  error?: string;
}

/** Result wrapper for any agent execution */
export interface AgentResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  logs: AgentLog[];
}

/** Base interface that all agents must implement */
export interface IAgent<TInput, TOutput> {
  name: string;
  execute(input: TInput): Promise<AgentResult<TOutput>>;
}
